name: Through The Stack - Hacking the Stack one Byte at a Time
description: Tips and tutorials for all elements of the Web Development Stack
author: Anthony Desmier
author_email: contact@throughthestack.com
url: https://www.throughthestack.com
permalink: /blog/:categories/:title/

# not sure if this is needed??
include: 
  - _pages
  - _redirects

gems:
  - jekyll-sitemap

# markdown engine to use
markdown: kramdown
# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  # colour stylings can be found at assets/css/vendor/_rouge-style.scss
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'codeblock-highlight'
    # line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - assets/css/modules
  - assets/css/main.scss
  - assets/fonts/font-awesome
  - assets/scripts/plugins
