name: DevBytes - Web Development in small Bytes
description: Tips and tutorials to help you with Web Development
author: Anthony Desmier
author_email: anthony@adesmier.com
url: http://10.250.2.134:3000
permalink: /blog/:categories/:title/

include: ['_pages']

# markdown engine to use
markdown: kramdown
# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  # colour stylings can be found at assets/css/vendor/_rouge-style.scss
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'codeblock-highlight'
    # line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - assets/css/modules
  - assets/css/main.scss
  - assets/images
  - assets/fonts/font-awesome
